### ISSUE TITLE
Container creation on Windows node fails because "Failed create pod sandbox"

### ISSUE THREAD

**Issue by andreacasini** [openshift/openshift-windows#19]
Ansible playbooks execution is successful.
Pods cannot start on the Windows Host.
Pods scheduled on the linux host via NodeSelector run fine.

### Version
oc v3.11.51
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v3.11.51
kubernetes v1.11.0+d4cacc0
VMware vSphere 6.5 U2

### Node Status
NAME                            STATUS    ROLES                  AGE       VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION              CONTAINER-RUNTIME
ocp-win-master.domain.local   Ready     compute,infra,master   18h       v1.11.0+d4cacc0   172.20.25.2   <none>        Red Hat Enterprise Linux         3.10.0-957.1.3.el7.x86_64   docker://1.13.1
ocp-win-worker                  Ready     compute                2h        v1.11.3           10.128.1.2    <none>        Windows Server 2019 Datacenter   10.0.17763.107
                                docker://18.9.0

### Steps to reproduce
1. Install a VMware VM with RHEL 7.5
2. Install a VMware VM with Windows Server Core 2019
3. Follow README.md instructions

### Current Result
  Normal   Scheduled               51s                 default-scheduler        Successfully assigned sinthera/iis-76bb88d545-l7klk to ocp-win-worker
  Warning  FailedSync              46s                 kubelet, ocp-win-worker  error determining status: rpc error: code = Unknown desc = Error: No such container: de395b520c81ff41f1893c2f80c6c10b1be831ae0e2c79bd47bbf38bfde9f1b1
  Warning  FailedCreatePodSandBox  38s (x12 over 50s)  kubelet, ocp-win-worker  Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container for pod "iis-76bb88d545-l7klk": Error response from daemon: security option not supported: label
  Normal   SandboxChanged          37s (x12 over 49s)  kubelet, ocp-win-worker  Pod sandbox changed, it will be killed and re-created.

The only potential error I can find is related to networking on Windows side:

C:\k\hybrid\logs> cat .\kubeovn.log
time="2019-01-04T12:55:38+01:00" level=info msg="Parsed config file C:\\cni\\ovn_k8s.conf"
time="2019-01-04T12:55:38+01:00" level=info msg="Parsed config: {Default:{MTU:0 ConntrackZone:0 EncapType: EncapIP:172.20.25.3} Logging:{File: Level:0} CNI:{ConfDir: Plugin: WinHNSNetworkID:} Kubernetes:{Kubeconfig: CACert:/k/ca.crt APIServer:https://ocp-win-master.sinthera.local:8443 Token:eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvdm4ta3ViZXJuZXRlcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvdm4tdG9rZW4temRjeDIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoib3ZuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTg1ZDUzNzYtMGY4Zi0xMWU5LWI2NGQtMDA1MDU2YTZkM2FiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Om92bi1rdWJlcm5ldGVzOm92biJ9.HsAwdKAF9UzHJTt-4ea40h8_LYwiUGcntDla28OjaR0QkI7argI-2aprhcnctqymMqmLDCpPlRLPIUtXMifuqA6ktFHHWLL0RaMjg6JqGA03c9xzFwNe7f4Zar1DZdYIbh6PggpZtBb2uULKvytaFjcI1s3VM08Sy9IpvBUbaQgNZv6yWhSjZuSLrme5EiezrOdAWZ1oXMhUGJZlwRcNMSrl67pVQYqxTPWHw4nNjttofMKeljiEWZ7PZ2tkRMufoNaP-x7UETNJBFNUKCflIi2nuE6HPDiZMDfib4AaZvToRcni85t-7YMcppCvXOG4MmToyyAyyDvsxIhPlPxZoA} OvnNorth:{Address:tcp://172.20.25.2:6641 ClientPrivKey: ClientCert: ClientCACert: ServerPrivKey: ServerCert: ServerCACert:} OvnSouth:{Address:tcp://172.20.25.2:6642 ClientPrivKey: ClientCert: ClientCACert: ServerPrivKey: ServerCert: ServerCACert:}}"
time="2019-01-04T12:55:38+01:00" level=info msg="Node ocp-win-worker ready for ovn initialization with subnet 10.128.1.0/24"
time="2019-01-04T12:56:02+01:00" level=info msg="CNI server started"
time="2019-01-04T15:01:56+01:00" level=info msg="Waiting for DEL result for pod /"
time="2019-01-04T15:01:56+01:00" level=info msg="Dispatching pod network request &{DEL   3962d2bef74e0218abc2a9500693a90d10c5630568f5fa680ff89948e6f858b3  eth0 0xc0423fc320 0xc04203efc0}"
time="2019-01-04T15:01:56+01:00" level=warning msg="cleanup failed, required CNI variable missing from args: &{DEL   3962d2bef74e0218abc2a9500693a90d10c5630568f5fa680ff89948e6f858b3  eth0 0xc0423fc320 0xc04203efc0}"
time="2019-01-04T15:01:56+01:00" level=info msg="Returning pod network request &{DEL   3962d2bef74e0218abc2a9500693a90d10c5630568f5fa680ff89948e6f858b3  eth0 0xc0423fc320 0xc04203efc0}, result  err <nil>"

### Worth Noting
IP address of the worker on the OVN Network is 10.128.1.2/24.
IP address of the master on the OVN Network is 10.128.0.2/24.
Master and Worker can ping on the OVN Network.
Current RHEL version is 7.6 (not 7.5 as mentioned in the instructions) since the installation of docker require some new selinux packages that provoke a yum update; tried to set version to 7.5 with subscription-manager but playbook fails to install docker.
Current Windows Version is 1809 and not 1803 as mentioned in the instructions.
If I "docker run -it microsoft/windowsservercore:latest" on the Windows node it works fine but once inside the container if I run "ipconfig" I have no IP address configuration returned and no network interface shows (if I run the same on the Windows host before running the playbooks I can see the IP inside the container)

Below is the deployment I tried:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iis
spec:
  template:
    metadata:
      labels:
        app: iis
    spec:
      containers:
      - name: iis
        image: mcr.microsoft.com/windows/servercore/iis
      nodeSelector:
       beta.kubernetes.io/os: windows
```
### Expexted Result
Pods should run on the Windows node just like on the linux node.

**Comment by andreacasini** [comment]
After rebooting the Windows node the following happened:

- oc get nodes shows the node in a "Not Ready" state.
- Windows System Log show the following entry every second:
```
The Open vSwitch Service service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 0 milliseconds: Restart the service.
```
- Windows Application Log show the following entry every second:
```
Faulting application name: ovs-vswitchd.exe, version: 0.0.0.0, time stamp: 0x5c1cee6b
Faulting module name: ovs-vswitchd.exe, version: 0.0.0.0, time stamp: 0x5c1cee6b
Exception code: 0xc0000409
Fault offset: 0x00000000001cbcb4
Faulting process id: 0xa60
Faulting application start time: 0x01d4a6050d8449e4
Faulting application path: C:\Program Files\Cloudbase Solutions\Open vSwitch\bin\ovs-vswitchd.exe
Faulting module path: C:\Program Files\Cloudbase Solutions\Open vSwitch\bin\ovs-vswitchd.exe
Report Id: aa59318b-3207-4ac3-a5cd-508a6402d2be
Faulting package full name:
Faulting package-relative application ID:
```
- ovs-vswitchd.log shows following entries repetedely:
```
vs_numa|INFO|Discovered 0 NUMA nodes and 0 CPU cores
econnect|INFO|unix:C:\ProgramData\openvswitch\db.sock: connecting...
econnect|INFO|unix:C:\ProgramData\openvswitch\db.sock: connected
log|INFO|opened log file C:\Program Files\Cloudbase Solutions\Open vSwitch\logs\ovs-vswitchd.log
```
- ovn-controller.log shows following entries repetedely (note that files are existing and ACLs seem ok):
```
rconn|WARN|unix:C:\ProgramData\openvswitch\/br-int.mgmt: connection failed
stream_windows|ERR|Could not connect to named pipe: The system cannot find the file specified.
rconn|WARN|unix:C:\ProgramData\openvswitch\/br-int.mgmt: connection failed (No such file or directory)
```

**Comment by juangps96** [comment]
Where is the complete exercise to join a Windows Worker Node to OpenShift?

**Comment by glennswest** [comment]
this looks like you dont have the right attirbutes on the windows containers. Please look at winpacman to see how it setup. Also note the image must match, which you can also see in glennswest/winpacman.
