### ISSUE TITLE
cni config uninitialized

### ISSUE THREAD

**Issue by mmgil** [openshift/openshift-windows#20]
Hi,

When i will trying deploy using:

ansible-playbook -i hosts ../openshift-ansible/playbooks/deploy_cluster.yml

The TASK [openshift_cluster_monitoring_operator : Wait for the ServiceMonitor CRD to be created] Failed.

In my investigation i receive the following error in /var/log/messages: 

> Jan  8 00:08:08 master1 origin-node: E0108 00:08:08.374671   39226 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"
> Jan  8 00:08:11 master1 origin-node: W0108 00:08:11.933121   39226 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
> Jan  8 00:08:11 master1 origin-node: E0108 00:08:11.933340   39226 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
> Jan  8 00:08:16 master1 origin-node: W0108 00:08:16.937125   39226 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
> Jan  8 00:08:16 master1 origin-node: E0108 00:08:16.942596   39226 kubelet.go:2101] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

but the ansible-playbook -i inventory/hosts.localhost ../openshift-windows/3.11/standalone/multihost.yml is executed with success.

and auto-install-ovn.sh so too is installed with success

**Comment by jchraibi** [comment]
any update on this topic ? I am getting exactly the same issue, thanks.
