### ISSUE TITLE
Windows Node fails "Windows | Check Windows SDN setup task"

### ISSUE THREAD

**Issue by ericklau** [openshift/openshift-windows#25]
Steps to reproduce:

Install a VMware VM with RHEL 7.5
Install a VMware VM with Windows Server Core 2019
Follow README.md instructions

Error Message:

TASK [Windows | Check Windows SDN setup task] **********************************
fatal: [winnode02.irscsv.local]: FAILED! => {"changed": true, "cmd": "$ErrorActionPreference = \"Stop\"\n $taskName = \"setup_sdn\"\n if((Get-ScheduledTask -TaskName $taskName).State -ne 'Ready') {\n Throw \"The scheduled task $taskName is not ready\"\n }\n Write-Output \"The scheduled task is ready\"\n $statusFile = \"C:\\k\\hybrid\\3.11\\bin\\${taskName}.status\"\n if(!(Test-Path $statusFile)) {\n Write-Output \"Status file doesn't exist. Skipping\"\n exit 0\n }\n $exitCode = Get-Content $statusFile\n if($exitCode -ne 0) {\n Throw \"Scheduled task ${taskName} returned with error\"\n }\n Write-Output \"Scheduled task ${taskName} returned with success\"", "delta": "0:00:01.236914", "end": "2019-07-29 03:53:00.383253", "msg": "non-zero return code", "rc": 1, "start": "2019-07-29 03:52:59.146339", "stderr": "Scheduled task setup_sdn returned with error\r\nAt line:14 char:2\r\n+  Throw \"Scheduled task ${taskName} returned with error\"\r\n+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OperationStopped: (Scheduled task ...rned with error:String) [], RuntimeException\r\n    + FullyQualifiedErrorId : Scheduled task setup_sdn returned with error", "stderr_lines": ["Scheduled task setup_sdn returned with error", "At line:14 char:2", "+  Throw \"Scheduled task ${taskName} returned with error\"", "+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : OperationStopped: (Scheduled task ...rned with error:String) [], RuntimeException", "    + FullyQualifiedErrorId : Scheduled task setup_sdn returned with error"], "stdout": "The scheduled task is ready\r\n", "stdout_lines": ["The scheduled task is ready"]}

Question:

I know this repo is new has anyone actually deployed this windows + linux environment successfully?

**Comment by glennswest** [comment]
Many times 
U need the doc that part of the dev program

Stephen can send u

Its for 3.11 and u need a esxi env
And the right version of windows iso

And the ocp needs to be stood up using the allinone scripts

**Comment by ericklau** [comment]
I am trying to deploy this solution in amazon's ec2 VM with Windows Server Core 2019 w/ containers (pre-built ami from amazon) as well as RHEL 7.5.  Any documentation or help would be great!  So esxi should be downloaded it seems if its not on the win system already?

Is it possible to add a windows node to an existing OpenShift Origin Linux Cluster? 

I know I asked a lot of questions but I am really interested in this solution and I think this will be a great use-case!  Thanks again for your help!
