### ISSUE TITLE
Complete Setup Guide for OpenShift Origin 3.10

### ISSUE THREAD

**Issue by nichochen** [openshift/openshift-windows#9]
Windows Containers is listed as Dev Preview for OpenShift Origin 3.10. Are there any documentation on how to setup Windows Containers for 3.10?

**Comment by cooktheryan** [comment]
Not yet. This process is still currently WIP

**Comment by juangps96** [comment]
Same Question: Are there any documentation on how to setup Windows Containers for 3.10?

**Comment by andreacasini** [comment]
Just follow the readme

**Comment by glennswest** [comment]
Is recommend you use the 3.11 and make sure its a new cluster setup with the allinone scripts

**Comment by michaelcourcy** [comment]
I can't find the allinone scripts. Did I miss something ?

**Comment by glennswest** [comment]
Under standalone

**Comment by michaelcourcy** [comment]
Thanks i missed it.
